### -*- mode: org; -*-
#+STARTUP: hidestars #+STARTUP: odd #+STARTUP: logdone #+STARTUP: nofninline
#+STYLE: <link rel="stylesheet" type="text/css" href="style.css" />

        Программа для прошивки флэш-памяти в системах использующих кристалл Мультикор
#+BEGIN_CENTER
Сопроводительная документация \\
\\
October 27, 2009, 23:45
#+END_CENTER

* Ограничения

Программа для прошивки флэш-памяти (далее "флэшер") предназначена для записи
информации в энергонезависимую флэш-память на платах построенных на платформе
Elvees Multicore, используя управляющий отладочный интерфейс JTAG посредством
интерфейсных адаптеров EPP и USB.

Флэшер функционирует в средах Linux/x86 и win32/x86.

Поддерживаются, потенциально, все типы флэш-памяти использующие наборы команд
Intel и AMD, однако тестирование проводилось только с чипами следующих моделей:
  - SST38VF6401B (набор команд AMD/Spansion)
  - MT28F640J3 (набор команд Intel)

При указании имён файлов нельзя использовать знак двоеточия ':', что исключает
возможность задания абсолютных путей на платформах win32.
Также, исключены пробелы.

При задании численных значений, необходимо использовать шестнадцатиричную форму,
без каких-либо префиксов или суффиксов ("0x", "h" или же "#x").

* Механизм работы программы и её интерфейс

Полный прогон программы состоит из четырёх фаз:
  - фаза поиска групы флэш-чипов
  - фаза записи
  - фаза проверки
  - фаза печати

Активация фаз осуществляется ключём индивидуальным для каждой из них, кроме фазы
поиска, осуществляемой автоматически при осуществлении записи.

Фаза записи контролируется ключами =--raw-file= и =--elf-file=, осуществляющими
задание записи "сырого" и ELF-файлов, соответственно. Каждый из этих ключей может
быть указан единожды, причём ключ =--raw-file= требует добавочного ключа =--raw-base=,
для задания базового адреса записи.

Следует отметить, что ввиду того что, как было указано выше, фаза записи
подразумевает фазу поиска флэш-памяти, необходимо задание добавочного параметра,
указывающего базовый адрес самой флэш-памяти. Этот адрес задаётся с помощью ключа
=--flash-base=, и имеет значение по умолчанию удобное для тестовых плат: #xbfc00000.

Фаза проверки по умолчанию включена и выключается с помощью флага =--no-check=.

Фаза печати активируется ключём =--dump-base= и требует добавочный ключ =--dump-size=.

Ключ =--preserve-holes= контролирует сохранение информации в блоках стирания
содержащих записываемые секциями.

Ключ =--verbose= контролирует количество выдаваемой статусной информации.

Флаг =--help= выдаёт справку на английском языке. Справка выдаётся, также, и при
отсутствии ключей.

* Особенности установки драйверов адаптеров JTAG EPP и USB

Для функционирования отладчика JTAG, предоставляющего инфраструктуру для флэшера,
требуется установка драйвера адаптера устанавливающего связь с JTAG TAP.

Драйвер EPP адаптера устанавливается отладчиком автоматически, причём требуется
чтобы файл mcdbio.sys устанавливаемого драйвера находился в одной папке с
исполняемым файлом флэшера.

В случае с USB, драйвер необходимо устанавливать вручную, путём подключения
адаптера и представления системе Windows необходимой информации о расположении
inf-файла драйвера через всплывающее окно, автоматически появляющееся при
подключении адаптера.
